In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-1.3.5-cp310-cp310-win_amd64.whl (10.2 MB)
Collecting numpy>=1.21.0
  Downloading numpy-1.21.5-cp310-cp310-win_amd64.whl (14.0 MB)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\sangeunne\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2017.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: six>=1.5 in c:\users\sangeunne\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.21.5 pandas-1.3.5 pytz-2021.3

WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\SangeunnE\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [10]:
# ======================================(0): pandas 시작
import pandas as pd
print(pd.__version__)

1.3.5

In [11]:
# ======================================(1): 파일 불러오기
df = pd.read_csv('./film_festival_2021.csv', encoding='cp949') # 인코딩 해와야 함 룰루~
df

,연도,영화제,장르,출품작,감독,출품분야,수상내역,수상인
0,2021,런던 리프트오프 영화제,일반(종합),뉴타운 생존자 수색작전,강민구,December 2021 Trendsetter Features,NaN,강민구
1,2021,제주영화제,일반(종합),저는 잘 있어요,문재웅,제주트멍,NaN,NaN
2,2021,제주영화제,일반(종합),낮과 달,이영아,개막작,NaN,NaN
3,2021,제주영화제,일반(종합),자산어보,이준익,아일랜드시네마,NaN,NaN
4,2021,제주영화제,일반(종합),바다의 양식,NaN,제주트멍,NaN,NaN
...,...,...,...,...,...,...,...,...
1271,2021,케임브리지영화제,일반(종합),조지아,제이 박,국제경쟁,NaN,NaN
1272,2021,족자-넷팩아시안영화제,일반(종합),조지아,제이 박,국제경쟁,NaN,NaN
1273,2021,포틀랜드 영화제,일반(종합),조지아,제이 박,극영화 단편경쟁,대상,NaN
1274,2021,괌 국제영화제,일반(종합),조지아,제이 박,단편경쟁,대상,NaN
1275,2021,도큐페스트,일반(종합),조지아,제이 박,경쟁,NaN,NaN

In [13]:
df.head()

,연도,영화제,장르,출품작,감독,출품분야,수상내역,수상인
0,2021,런던 리프트오프 영화제,일반(종합),뉴타운 생존자 수색작전,강민구,December 2021 Trendsetter Features,NaN,강민구
1,2021,제주영화제,일반(종합),저는 잘 있어요,문재웅,제주트멍,NaN,NaN
2,2021,제주영화제,일반(종합),낮과 달,이영아,개막작,NaN,NaN
3,2021,제주영화제,일반(종합),자산어보,이준익,아일랜드시네마,NaN,NaN
4,2021,제주영화제,일반(종합),바다의 양식,NaN,제주트멍,NaN,NaN

In [14]:
print(df.columns)

Index(['연도', '영화제', '장르', '출품작', '감독', '출품분야', '수상내역', '수상인'], dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      1276 non-null   int64
 1   영화제     1276 non-null   object
 2   장르      1276 non-null   object
 3   출품작     1276 non-null   object
 4   감독      1141 non-null   object
 5   출품분야    1083 non-null   object
 6   수상내역    222 non-null    object
 7   수상인     147 non-null    object
dtypes: int64(1), object(7)
memory usage: 79.9+ KB

In [19]:
df.shape # 2021 년도 개수

(1276, 8)

In [22]:
df.dtypes

연도       int64
영화제     object
장르      object
출품작     object
감독      object
출품분야    object
수상내역    object
수상인     object
dtype: object

In [24]:
df.출품작.dtypes #?????????? column 명 바꿔야 할까?  => df.columns = ['col1', 'col2', ... ]

dtype('O')

In [29]:
df.count() # 데이터 개수 확인 => `NaN 값이 있구나` 정도 확인

연도      1276
영화제     1276
장르      1276
출품작     1276
감독      1141
출품분야    1083
수상내역     222
수상인      147
dtype: int64

In [30]:
print(type(df.count()))

<class 'pandas.core.series.Series'>

* 그냥 끄적인 데이터 상태 확인하는 과정 (Series 데이터)

## DB1 에서 중복값 제거
- `출품작` && `감독`

In [10]:
df.drop_duplicates(['출품작']) # A

,연도,영화제,장르,출품작,감독,출품분야,수상내역,수상인
0,2021,런던 리프트오프 영화제,일반(종합),뉴타운 생존자 수색작전,강민구,December 2021 Trendsetter Features,NaN,강민구
1,2021,제주영화제,일반(종합),저는 잘 있어요,문재웅,제주트멍,NaN,NaN
2,2021,제주영화제,일반(종합),낮과 달,이영아,개막작,NaN,NaN
3,2021,제주영화제,일반(종합),자산어보,이준익,아일랜드시네마,NaN,NaN
4,2021,제주영화제,일반(종합),바다의 양식,NaN,제주트멍,NaN,NaN
...,...,...,...,...,...,...,...,...
1220,2021,월드 필름 카니발 싱가포르,일반(종합),이발소,임윤기,Movie of the Month - April : Short Films,Short Films Winner,임윤기
1226,2021,LA국제단편영화제,단편,"엄마, 영숙",NaN,경쟁 - 아시아 섹션,NaN,NaN
1229,2021,한중국제영화제,일반(종합),추운겨울에도 빛이 있다.,최정한,단편영화제,심사위원상,최정한
1230,2021,LA독립단편영화제,단편,죽고 싶은 날에 한하여,김묘욱,Bronze Awards: September 2021,음악상,장용진
1254,2021,대한민국 대학영화제,일반(종합),스마일 클럽,최은우,경쟁 진출,NaN,NaN

In [11]:
df.drop_duplicates(['출품작', '감독']) # A and B

,연도,영화제,장르,출품작,감독,출품분야,수상내역,수상인
0,2021,런던 리프트오프 영화제,일반(종합),뉴타운 생존자 수색작전,강민구,December 2021 Trendsetter Features,NaN,강민구
1,2021,제주영화제,일반(종합),저는 잘 있어요,문재웅,제주트멍,NaN,NaN
2,2021,제주영화제,일반(종합),낮과 달,이영아,개막작,NaN,NaN
3,2021,제주영화제,일반(종합),자산어보,이준익,아일랜드시네마,NaN,NaN
4,2021,제주영화제,일반(종합),바다의 양식,NaN,제주트멍,NaN,NaN
...,...,...,...,...,...,...,...,...
1220,2021,월드 필름 카니발 싱가포르,일반(종합),이발소,임윤기,Movie of the Month - April : Short Films,Short Films Winner,임윤기
1226,2021,LA국제단편영화제,단편,"엄마, 영숙",NaN,경쟁 - 아시아 섹션,NaN,NaN
1229,2021,한중국제영화제,일반(종합),추운겨울에도 빛이 있다.,최정한,단편영화제,심사위원상,최정한
1230,2021,LA독립단편영화제,단편,죽고 싶은 날에 한하여,김묘욱,Bronze Awards: September 2021,음악상,장용진
1254,2021,대한민국 대학영화제,일반(종합),스마일 클럽,최은우,경쟁 진출,NaN,NaN

In [12]:
# ======================================(2): 중복 제거
db2_raw = df.drop_duplicates(['출품작', '감독'], ignore_index=True) # 인덱스 새로 설정
db2_raw

,연도,영화제,장르,출품작,감독,출품분야,수상내역,수상인
0,2021,런던 리프트오프 영화제,일반(종합),뉴타운 생존자 수색작전,강민구,December 2021 Trendsetter Features,NaN,강민구
1,2021,제주영화제,일반(종합),저는 잘 있어요,문재웅,제주트멍,NaN,NaN
2,2021,제주영화제,일반(종합),낮과 달,이영아,개막작,NaN,NaN
3,2021,제주영화제,일반(종합),자산어보,이준익,아일랜드시네마,NaN,NaN
4,2021,제주영화제,일반(종합),바다의 양식,NaN,제주트멍,NaN,NaN
...,...,...,...,...,...,...,...,...
638,2021,월드 필름 카니발 싱가포르,일반(종합),이발소,임윤기,Movie of the Month - April : Short Films,Short Films Winner,임윤기
639,2021,LA국제단편영화제,단편,"엄마, 영숙",NaN,경쟁 - 아시아 섹션,NaN,NaN
640,2021,한중국제영화제,일반(종합),추운겨울에도 빛이 있다.,최정한,단편영화제,심사위원상,최정한
641,2021,LA독립단편영화제,단편,죽고 싶은 날에 한하여,김묘욱,Bronze Awards: September 2021,음악상,장용진
642,2021,대한민국 대학영화제,일반(종합),스마일 클럽,최은우,경쟁 진출,NaN,NaN

> https://mizykk.tistory.com/93
> https://nittaku.tistory.com/124

## null 값 처리
- 개수 확인
-

In [6]:
# ======================================(3): null 값 개수 확인
db2_raw['감독'].isnull().sum()

95

In [7]:
db2_raw['수상내역'].isnull().sum()

596

In [52]:
db2_raw

,연도,영화제,장르,출품작,감독,출품분야,수상내역,수상인
0,2021,런던 리프트오프 영화제,일반(종합),뉴타운 생존자 수색작전,강민구,December 2021 Trendsetter Features,NaN,강민구
1,2021,제주영화제,일반(종합),저는 잘 있어요,문재웅,제주트멍,NaN,NaN
2,2021,제주영화제,일반(종합),낮과 달,이영아,개막작,NaN,NaN
3,2021,제주영화제,일반(종합),자산어보,이준익,아일랜드시네마,NaN,NaN
4,2021,제주영화제,일반(종합),바다의 양식,NaN,제주트멍,NaN,NaN
...,...,...,...,...,...,...,...,...
638,2021,월드 필름 카니발 싱가포르,일반(종합),이발소,임윤기,Movie of the Month - April : Short Films,Short Films Winner,임윤기
639,2021,LA국제단편영화제,단편,"엄마, 영숙",NaN,경쟁 - 아시아 섹션,NaN,NaN
640,2021,한중국제영화제,일반(종합),추운겨울에도 빛이 있다.,최정한,단편영화제,심사위원상,최정한
641,2021,LA독립단편영화제,단편,죽고 싶은 날에 한하여,김묘욱,Bronze Awards: September 2021,음악상,장용진
642,2021,대한민국 대학영화제,일반(종합),스마일 클럽,최은우,경쟁 진출,NaN,NaN

In [59]:
db2_raw.query('출품작 == "바다의 양식"') # 특정 값을 포함한 행 추출 => 중복없음 확인

     연도    영화제      장르     출품작   감독  출품분야 수상내역  수상인
4  2021  제주영화제  일반(종합)  바다의 양식  NaN  제주트멍  NaN  NaN

> https://zephyrus1111.tistory.com/46

## 필요한 열(Columns) 추출
- index , '출품작', '감독'

In [13]:
# ======================================(4-1): 의미있는 col 만 추출
db2 = db2_raw[['출품작', '감독']]
db2

               출품작   감독
0     뉴타운 생존자 수색작전  강민구
1         저는 잘 있어요  문재웅
2             낮과 달  이영아
3             자산어보  이준익
4           바다의 양식  NaN
..             ...  ...
638            이발소  임윤기
639         엄마, 영숙  NaN
640  추운겨울에도 빛이 있다.  최정한
641   죽고 싶은 날에 한하여  김묘욱
642         스마일 클럽  최은우

[643 rows x 2 columns]

## 감독 column NaN 값이면 제거
- NaN 처리 방법 고민 전에 우선 BE 에 넘겨야 해서 관련 행 제거하고 진행

In [15]:
# ======================================(4-2): NaN(결측값) 행 제거
db2_nan = db2.dropna(axis=0)
db2_nan

               출품작   감독
0     뉴타운 생존자 수색작전  강민구
1         저는 잘 있어요  문재웅
2             낮과 달  이영아
3             자산어보  이준익
5           섬이없는지도  김성은
..             ...  ...
637        조의(JOY)  권용재
638            이발소  임윤기
640  추운겨울에도 빛이 있다.  최정한
641   죽고 싶은 날에 한하여  김묘욱
642         스마일 클럽  최은우

[548 rows x 2 columns]

In [20]:
# ======================================(): column 명 영문 변경
db2_nan.columns = ['title', 'director']
db2_nan

             title director
0     뉴타운 생존자 수색작전      강민구
1         저는 잘 있어요      문재웅
2             낮과 달      이영아
3             자산어보      이준익
5           섬이없는지도      김성은
..             ...      ...
637        조의(JOY)      권용재
638            이발소      임윤기
640  추운겨울에도 빛이 있다.      최정한
641   죽고 싶은 날에 한하여      김묘욱
642         스마일 클럽      최은우

[548 rows x 2 columns]

In [9]:
# ======================================(5-1): csv 로 저장
db2.to_csv("db2_title_2021.csv", index=True, header=True)

In [21]:
# ======================================(5-2): csv 로 저장
db2_nan.to_csv("db2_title_NaN_2021.csv", index=True, header=True)