In [80]:
import pandas as pd
import urllib.request
import time
import json

### 대표 장르 18개에 해당하는 각각의 영화의 제목, 감독, 장르를 입력해준다.

In [81]:
rep_movie = pd.DataFrame({'title': ['기생충','극한직업','해리포터','센과 치히로의 행방불명','어바웃타임','소수의견','올드보이','더셀','컨저링','노예12년','스파이더맨','해운대','인터스텔라','1917','스쿨 오브 락','말아톤','콜 미 바이 유어 네임','라이프 오브 파이'],
                         'director' :['봉준호', '이병헌', '데이빗 예이츠','미야자키 하야오','리차드 커티스','김성제','박찬욱','타셈 싱','마이클 차베즈','스티브 맥퀸','존 왓츠','윤제균','크리스토퍼 놀란','샘 맨데스','리차드 링클래이터','정윤철','루카 구아다니노','이안'],
                         'genre': ['드라마','코메디','판타지','가족','멜로','사회','스릴러','실험','공포','인권','액션','자연','SF','역사','뮤직','스포츠','동성애','어드벤처']})
rep_movie

           title   director genre
0            기생충        봉준호   드라마
1           극한직업        이병헌   코메디
2           해리포터    데이빗 예이츠   판타지
3   센과 치히로의 행방불명   미야자키 하야오    가족
4          어바웃타임    리차드 커티스    멜로
5           소수의견        김성제    사회
6           올드보이        박찬욱   스릴러
7             더셀       타셈 싱    실험
8            컨저링    마이클 차베즈    공포
9          노예12년     스티브 맥퀸    인권
10         스파이더맨       존 왓츠    액션
11           해운대        윤제균    자연
12         인터스텔라   크리스토퍼 놀란    SF
13          1917      샘 맨데스    역사
14       스쿨 오브 락  리차드 링클래이터    뮤직
15           말아톤        정윤철   스포츠
16  콜 미 바이 유어 네임   루카 구아다니노   동성애
17     라이프 오브 파이         이안  어드벤처

In [82]:
client_id =''
url = 'http://api.koreafilm.or.kr/openapi-data2/wisenut/search_api/search_json2.jsp?collection=kmdb_new2'
option = "&listCount=500&detail=Y&ServiceKey=IG9S02XET4ZZ509DATVC"

In [96]:
plot = []
poster = []
for i in range(0,len(rep_movie.title)):
    query = "&title="+urllib.parse.quote(rep_movie.title[i])+"&director="+urllib.parse.quote(rep_movie.director[i])
    url_query = url + query + option
    request = urllib.request.Request(url_query)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if(rescode == 200):
        response_body = json.load(response)
    else:
        print("Error code:"+rescode)
    if 'Result' in response_body['Data'][0]:
        for j in range(0,len(response_body['Data'][0]['Result'])):
            if rep_movie.title[i][0:3] in response_body['Data'][0]['Result'][j]['titleEtc']:
                plot.append(response_body['Data'][0]['Result'][j]['plots']['plot'][0]['plotText'])
                poster.append(response_body['Data'][0]['Result'][j]['posters'])
                break
            else:
                plot.append('')
                poster.append('')
                break
    else:
        plot.append('')
        poster.append('')
#포스터 이미지가 '|'를 기준으로 복수로 주어지는 경우가 있어서 맨 앞의 포스터만 사용했다.
img_link = []
for x in poster:
    if '|' in x:
        index = x.index('|')
        img_link.append(x[0:index])
    else:
        img_link.append(x)

In [99]:
rep_movie['plot'] = plot
rep_movie['img_link'] = img_link
#올드보이는 두 번째로 주어지는 포스터를 사용하기 위해 따로 바꿔주었다.
rep_movie.img_link[6] = 'http://file.koreafilm.or.kr/thm/02/00/03/56/tn_DPK06066A.jpg'

In [100]:
rep_movie.to_csv('rep_movies.csv', encoding='utf8', index = False)